### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Orxan88/PragmatechFoundationProject#1]
_Orxan, reponuzu ümumi analiz etdim və yanlış olduğunu fikirləşdiyim bəzi məqamlar var. Məsələn, [commit mesajları](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali/) düzgün deyil. Repoya "README" faylı əlavə edib gördüyünüz işləri də oraya qeyd etsəniz yaxşı olar. Hər bir tapşırıq tapşırığın adına uyğun olaraq ümumi bir qovluqda yazılmalıdır, yəni qısaca açıqda html, css faylları olmalı deyil, tapşırığa uyğun qovluq yaradılmalı və bu fayllar da onun içində olmalıdır. Css faylları "css" adlı qovluqda olmalıdır. Kodlar çox səliqəsizdir, biraz səliqəli yazmağa çalışın və gördüyünüz işləri gündəlik olaraq GitHuba push edin, bu çox vacibdir. Uğurlar!🙂_

**Comment by Orxan88** [comment]
Nezrin salam. Yazdiginizi oxudum teoretik olalax ne dediyinizi basha
dushsemde praktiki neteri heyata kechirmek haqkinda hech bir fikirim yoxdu
men teze oyrenmeye bashladigim uchun cox yerde cetinlik var daha aydin izah
edses "yeni gore bileceyim shekilde problemi aradan qaldirmaga chaisharam"!
sagolun


вс, 14 нояб. 2021 г. в 14:44, Nəzrin İsbəndiyarova ***@***.***

**Comment by isbendiyarovanezrin** [comment]
_Orxan, əslində hər şeyi çox açıq və net yazmışam, amma yeni başladığınız üçün çətinlik çəkməyiniz çox normaldır. Ya biraz daha bəzi şeyləri öyrənəndən sonra qayıdıb yenidən oxuyarsınız rəyi ya da mentorunuzdan kömək istəyə bilərsiniz (yuxarıda göy rənglə yazılan sözün üstünə basanda düzgün commit yazmaq haqqında məqalə gəlir, ona da bir göz atarsınız).🙂_
